version: '3'
services:
  ripcord-ui:
    ports:
      - "80:3000"
      - "5000:5000"
    build: .
    depends_on:
      - "ripcord"

    env_file: .env

  ripcord:
    image: "kryptx/ripcord"
    ports:
      - "3000:3000"
